### ISSUE TITLE
Retry on connect is needed

### ISSUE THREAD

**Issue by Altai-man** [hythm7/Pakku#10]
Those are results of Blin run with zef: https://gist.github.com/Altai-man/143f217b2a19ef62dbac5a3c041d090a
Those are results of Blin run with Pakku: https://gist.github.com/Altai-man/4fbefe8ce18e9f583b1bcfd51e6c6822

Some related failures are:

```
🤓 FTC: ｢http://recman.pakku.org/archive/c7b2052a1665180806fb431c960ca60e7abda4b00d2bed1c94b1476334b27f05｣
Couldn't connect to server
  in method perform at /mnt/data/pakku/.repo/sources/A1B0D3262B1D5101E25E17813D11FC8291DDDA91 (LibCurl::Easy) line 667
  in method fetch at /mnt/data/pakku/.repo/sources/2AEEA026A8295BDE048513836A0688E0E7900714 (Pakku::Fetcher) line 19
```
and
```
🤓 FTC: ｢http://recman.pakku.org/archive/ba102ab8ee3d4c19c69261f2851bad73482e1205d84ffb6957aee134408bc85d｣
Couldn't connect to server
  in method perform at /mnt/data/pakku/.repo/sources/A1B0D3262B1D5101E25E17813D11FC8291DDDA91 (LibCurl::Easy) line 667
  in method fetch at /mnt/data/pakku/.repo/sources/2AEEA026A8295BDE048513836A0688E0E7900714 (Pakku::Fetcher) line 19
```

Can retrying make it more reliable?

**Comment by hythm7** [comment]
I think the error is because recman.pakku.org (which serves the meta and archives for the modules) has only 1 CPU and 4GB, and couldn't handle all requests sent from running Blin on a powerful machine. I'll try to reproduce and troubleshoot. Thanks for reporting.

**Comment by hythm7** [comment]
Also these modules were bisected because of the same issue, couldn't connect to the server to download the archive or the META file.
* Cofra
* Libarchive
* PDF::Font::Loader
* Whateverable
* p6doc

**Comment by Altai-man** [comment]
>I think the error is because recman.pakku.org (which serves the meta and archives for the modules) has only 1 CPU and 4GB, and couldn't handle all requests sent from running Blin on a powerful machine

You can contact @rba (same nickname on irc), there is a server machine used for blin before that I believe serves for RakuDist now. It has plenty of ram and cores IIRC.

**Comment by hythm7** [comment]
[this](https://github.com/hythm7/Pakku/commit/6c6dee87ade0280dc115d2038770167123ca88b1) should make the connection more reliable. I wasn't able to reproduce but I think this should fix it. Let me know if you see this issue again. Thanks.


> You can contact @rba (same nickname on irc), there is a server machine used for blin before that I believe serves for RakuDist now. It has plenty of ram and cores IIRC.

It would be great if `RecMan` moved to more powerful server. I will contact rba to see if its possible, but before that I need to make some cleaning on the server to make migration easier.
