### ISSUE TITLE
2020.11 Blin testing round with Pakku

### ISSUE THREAD

**Issue by Altai-man** [hythm7/Pakku#14]
https://gist.github.com/Altai-man/2ac42930e52adfe7140f5abcd1ce1d2f <- the results.

```
�[1;38;5;177m🦋 �[0m�[38;5;177mPRC: ｢HTTP::Supply｣ �[0m
�[1;38;5;14m🐞 �[0m�[38;5;14mSPC: ｢HTTP::Supply｣ �[0m
�[1;38;5;14m🐞 �[0m�[38;5;14mMTA: ｢HTTP::Supply:ver<0.5.0>:auth<github:zostay>:api<>｣ �[0m
�[1;38;5;42m🤓 �[0m�[38;5;42mFTC: ｢http://recman.pakku.org/archive/c3b1829c509f520254c4b1a9886245a0fa4c8770feb28bdd86e0ebf4fa84fbee｣ �[0m
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
�[1;38;5;42m🤓 �[0m�[38;5;42mFTC: ｢｣ �[0m
  in method fetch at /mnt/data/pakku/.repo/sources/2AEEA026A8295BDE048513836A0688E0E7900714 (Pakku::Fetcher) line 29
No such method 'IO' for invocant of type 'Any'.  Did you mean 'so'?
  in method fetch at /mnt/data/pakku/.repo/sources/2AEEA026A8295BDE048513836A0688E0E7900714 (Pakku::Fetcher) line 31
  in method add at /mnt/data/pakku/.repo/sources/19B6498876A77AD3B379A7F863F0363CC862340B (Pakku) line 51
  in submethod BUILD at /mnt/data/pakku/.repo/sources/D9CE102BBA40958D79F1A80CCF6625A8A3DE9D52 (Pakku::Guts) line 222
  in block <unit> at data/pakku/bin/pakku line 8
```

is the latest popular false positive error.

**Comment by hythm7** [comment]
@Altai-man thanks. [This](https://github.com/hythm7/Pakku/pull/15) should take care of the latest popular false positive error. Please try one more time when you get a chance.

**Comment by Altai-man** [comment]
The fix helped a lot. This is the latest run results: https://clbin.com/pMrWU
This is very good.

What concerns me is that tests output is too detailed and as a result it does not e.g. fit into a github gist. Is there a flag to make testing output less verbose, showing only failed ones?

**Comment by hythm7** [comment]
> What concerns me is that tests output is too detailed and as a result it does not e.g. fit into a github gist. Is there a flag to make testing output less verbose, showing only failed ones?

The testing output is visible in the output because Pakku is run with `verbose trace` option in Blin, if [removed](https://github.com/Raku/Blin/blob/master/lib/Blin/Tester/Pakku.rakumod#L39) (I can remove that if needed), the testing output will not appear. the test phase output will only show :
*  🦋 TST: ｢ ... ｣ # if dist test succeeded
*  💀 TST: ｢ ... ｣ # if dist test failed (but it will not show the error that caused the testing of the module to fail at the moment)

Also can run Pakku with 'nopretty' or 'np' option to remove color from output and get rid of terminal escape code in github gist.

**Comment by Altai-man** [comment]
>but it will not show the error that caused the testing of the module to fail at the moment

I guess there is no option in-between? Escape codes are ok.

**Comment by hythm7** [comment]
> > but it will not show the error that caused the testing of the module to fail at the moment
> 
> I guess there is no option in-between? Escape codes are ok.

Actually I take my previous comment back, if `verbose trace` is removed, it will default to `verbose info`, which will print `info, warn, error, fatal` levels to output.

Output example without `verbose trace` option:  

1- Installing a module [ test successful ] 
```
hythm@galaxy$ pakku add ./Grid
🦋 PRC: ｢./Grid｣ 
🦋 TST: ｢Grid:ver<0.0.4>:auth<github:hythm7>:api<*>｣ 
🦋 ADD: ｢Grid:ver<0.0.4>:auth<github:hythm7>:api<*>｣ 
-Ofun
```
2- Installing a module [changed a test to make it fail on purpose]:
```
hythm@galaxy$ pakku add ./Grid
🦋 PRC: ｢./Grid｣ 
🔔 # Failed test 'formatted grid' 
🔔 # at t/basic.t line 23 
🔔 # You failed 1 test of 44 
💀 TST: ｢Grid:ver<0.0.4>:auth<github:hythm7>:api<*>｣ 
Nofun
```


And the output for `warn` and `error` are below:

```
hythm@galaxy$ pakku verbose warn add ./Grid
🔔 # Failed test 'formatted grid' 
🔔 # at t/basic.t line 23 
🔔 # You failed 1 test of 44 
💀 TST: ｢Grid:ver<0.0.4>:auth<github:hythm7>:api<*>｣ 
Nofun
```
```
hythm@galaxy$ pakku verbose error add ./Grid
💀 TST: ｢Grid:ver<0.0.4>:auth<github:hythm7>:api<*>｣ 
Nofun
