### ISSUE TITLE
Fonts not supporting emojis

### ISSUE THREAD

**Issue by demostanis** [hythm7/Pakku#23]
I've been trying out Pakku, it worked fine installing a module, sadly it showed a square instead of a pretty butterfly
as my current Terminal's font does not support emojis.
Is there any way to disable them? Gently asking Pakku isn't working:
`pakku please nopretty dont add zef`
![image](https://user-images.githubusercontent.com/40673815/114916865-d4b37f80-9e14-11eb-9696-654a13bcbf73.png)
Thank you

**Comment by hythm7** [comment]
Hi,

If current terminal fonts doesn't support emojis you can override the log levels names in `<pakuu-dir>/pakku.cnf` file, in my system it's in `~/.pakku/pakku.cnf` (by uncommenting the log section in the config file and changing the names to what you prefer):


```

< log >
  trace name T:   # Trace
  debug name D:   # Debug
  info  name I:   # Info
  warn  name W:   # Warn
  error name E:   # Error
  fatal name F:   # Fatal

  # trace color reset
  # debug color green
  # info  color blue
  # warn  color yellow
  # error color magenta
  # fatal color red

```
```
> pakku please nopretty dont add zef
I: PRC: ｢zef｣
I: TST: ｢zef:ver<0.11.7>:auth<github:ugexe>:api<0>｣
-Ofun
```

**Comment by demostanis** [comment]
Thanks.
What about adding a comment to `resources/rakku.cnf` telling that
changing `info name I:` will remove the emojis, or replacing `name` by `prefix`?
Currently, it's not very self-explaining.

**Comment by hythm7** [comment]
Thanks, That makes sense. changed "name" to "prefix" with [this](https://github.com/hythm7/Pakku/commit/cee42115a2947673a68b5a01b244a8422269d379) commit

**Comment by demostanis** [comment]
<pre>
diff --git a/README.md b/README.md
index f0aea22..f290910 100644
--- a/README.md
+++ b/README.md
@@ -56,19 +56,26 @@ Overview
 🦋 BLD: ｢ ... ｣ → Built dist
 🦋 TST: ｢ ... ｣ → Tested dist
 🦋 RES: ｢ ... ｣ → Resource
-🦋 BIN: ｢ ... ｣ → Biniary
+🦋 BIN: ｢ ... ｣ → Binary
 🦋 ADD: ｢ ... ｣ → Added dist
 🐞 PAC: ｢ ... ｣ → Packing rakudo and dist 
 🦋 PAC: ｢ ... ｣ → Pack location
 🐞 WAI: ｢ ... ｣ → Waiting
 🔔 TOT: ｢ ... ｣ → Timed out
 💀 MTA: ｢ ... ｣ → Meta error
-💀 BLD: ｢ ... ｣ → Buld failed
+💀 BLD: ｢ ... ｣ → Build failed
 💀 TST: ｢ ... ｣ → Test failed
 💀 CNF: ｢ ... ｣ → Config error
 💀 CMD: ｢ ... ｣ → Command error
 ```
 
+* In case your terminal font does not support emojis, you can replace them by changing `prefix` values in the `< log >` section of your config file (usually `~/.pakku/pakku.cnf`):
+```
+< log >
+  trace prefix TRACE:
+  debug prefix DEBUG:
+```
+
 * `Pakku` uses [Pakku::RecMan](https://github.com/hythm7/Pakku-RecMan) recommendation manager to obtain distributions `META` info and archives.
 
 USAGE
</pre>

Here's a proposal of mention in the README.

**Comment by hythm7** [comment]
Updated, thanks.

**Comment by hythm7** [comment]
Closing. Please re-open in case there is still an issue. Thanks.
