### ISSUE TITLE
pakku verbose debug options not supported?

### ISSUE THREAD

**Issue by melezhik** [hythm7/Pakku#26]
Hi! I tried to use debug/verbose option in various fashions and every time get an error:

1. `pakku add notest verbose debug Foo` - https://ci.sparrowhub.io/report/2665 - FAIL
2. `pakku add notest debug Foo`  - https://ci.sparrowhub.io/report/2666 - FAIL 

without debug/verbose options the same command succeeds - https://ci.sparrowhub.io/report/2667 - PASS

HTH

Alexey

**Comment by hythm7** [comment]
Pakku has commands like (add remove upgrade list search download) and has options. there are two types of options:

1- per command specific options
These are the options that control Pakku commands like (add, remove ...). And when specifying these options, they must be placed after the command.

2- general options
These are the options that control the general behavior of Pakku (they are valid for all commands). And the general options must be placed after "pakku" and before the command (add, remove ...).

The "verbose" option is a general option that control the verbosity level, so it needs to be placed before the command.

Placing a general option after the command like `pakku add notest verbose debug Foo` will make Pakku thing you trying to install 3 distributions named (Foo, debug, verbose), the correct way is to use:

`pakku verbose debug add notest Foo`
 
Here "verbose debug" is a general option so its placed after pakku and before add, "notest" is a "add" command option, so its placed after add.

 Pakku full command is similar to:
 pakku < general options > < command > < specific command options > < distributions to install >

It can be confusing at first but once get used to it becomes simple.

The README file lists all options specific to each command, and the general options are in the section called "Pakku options". I think thats poorly named, i will update README with clearer description.

Thanks for reporting the issue.

**Comment by melezhik** [comment]
Makes a sense ! Thanks. Maybe worth to clarify this in the docs ? Maybe
it’s already there , I just did not notice it … ))

**Comment by hythm7** [comment]
You are definately right, it needs clarification in README i just updated my previous comment.
