### ISSUE TITLE
feature request : make an upgrade for "all"

### ISSUE THREAD

**Issue by dominix** [hythm7/Pakku#32]
still relying on zef for upgrade of all packages
please make it easy to upgrade all installed modules to current.

**Comment by hythm7** [comment]
I'm currently working on a feature that will let the user know if there are installed dists that can be upgraded. Once done, I will look into making it easy to upgrade all dists, which should be easier after implementing this feature.

**Comment by hythm7** [comment]
Updating all  installed dist to latest version is now available in `caria.1`  version by running `pakku update`.  This feature is currently `beta`, If you see any issue please open a new one. Thanks.
