### ISSUE TITLE
Migration to fez

### ISSUE THREAD

**Issue by 2colours** [hythm7/Pakku#37]
Hello,

I see this repo keeps bumping up on raku.land because it receives commits and that's a possible "dist update" for p6c.

I'd like to ask if there is a reason this software is still on p6c. In general, p6c is mostly there for just legacy reasons, software should preferably move to the "zef ecosystem" (using fez) which has proper integrity and versioning.

If this tool can be added there, it would be nice to publish it and remove the repo URL from the p6c master list.

Thank you.

**Comment by hythm7** [comment]
Hi 2colours,

There is no specific reason except that last time I tried moving to fez, I hit an issue when registering my fez account. That was 6+ months ago though, I will try registering  again later today or tomorrow, and move the software there. Thanks!

**Comment by hythm7** [comment]
Migrated to fez and [removed](https://github.com/Raku/ecosystem/commit/8b6a55469621dba9a19cd8b7a91f08a22c13d49a) from the legacy ecosystem.

**Comment by 2colours** [comment]
Thank you very much, nice and tidy. ^^
