### ISSUE TITLE
building pakku failed

### ISSUE THREAD

**Issue by skyter10086** [hythm7/Pakku#8]
✗ The spawned command 'curl' exited unsuccessfully (exit code: 7, signal: 0) 
✗   in method build at /home/zby/.zef/store/Pakku/./Build.rakumod line 8 
✗   in block <unit> at -e line 2 
✗  
☠ Build: Failed for dist [Pakku:ver<larva>:auth<github:hythm7>:api<*>] 
Nofun
The spawned command '/home/zby/.pakku/bin/pakku' exited unsuccessfully (exit code: 1, signal: 0)
  in sub MAIN at ./tools/install-pakku.raku line 94
  in block <unit> at ./tools/install-pakku.raku line 1

**Comment by hythm7** [comment]
@skyter10086 Thanks for reporting the issue, I have updated the module and this should be fixed now.

**Comment by hythm7** [comment]
Please reopen if you still seeing the issue. Thanks.
